PACKAGE_NAME=io.nekohasekai.sagernet
VERSION_NAME=0.8.1-rc04
VERSION_CODE=178

NAIVE_VERSION_NAME=143.0.7499.109-1
NAIVE_VERSION=59

PINGTUNNEL_VERSION_NAME=2.7
PINGTUNNEL_VERSION=3

RELAYBATON_VERSION_NAME=0.8.0-ech-1
RELAYBATON_VERSION=3

TROJAN_GO_VERSION_NAME=0.10.6
TROJAN_GO_VERSION=5

BROOK_VERSION_NAME=20220406
BROOK_VERSION=4

TROJAN_VERSION_NAME=1.16.0
TROJAN_VERSION=1

HYSTERIA_VERSION_NAME=2.6.6
HYSTERIA_VERSION=24

MIERU_VERSION_NAME=3.29.0
MIERU_VERSION=53

TUIC_VERSION_NAME=1.4.6
TUIC_VERSION=9
